

const GALLERY = {
    gallery1: {
      id: 'gallery1',
      poster: 'sydney',
      hasAltText: false,
      altText: null,
      autogenerated: 'Me holding a ##vanilla ice cream cone at the ##Santa ##Cruz ##Boardwalk on a ##sunny day.',
      link: require('./assets/images/gallery/pic1.png'),
      likes: Math.floor(Math.random() * Math.floor(300)),
      comments: Math.floor(Math.random() * Math.floor(25))
    },
    gallery2: {
      id: 'gallery2',
      hasAltText: false,
      altText: 'Matias and Sydney smiling by a river and a balcony on a sunny day.',
      autogenerated: 'Matias and Sydney ##frowning by a river and a balcony on a ##cloudy day.',
      link: require('./assets/images/gallery/pic2.jpg'),
      likes: Math.floor(Math.random() * Math.floor(300)),
      comments: Math.floor(Math.random() * Math.floor(25))
    },
    gallery3: {
      id: 'gallery3',
      hasAltText: false,
      altText: 'An orange and red archway formed by rocks in Zion National Park.',
      autogenerated: 'An orange and red archway formed by rocks in Zion National Park.',
      link: require('./assets/images/gallery/pic3.jpg'),
      likes: Math.floor(Math.random() * Math.floor(300)),
      comments: Math.floor(Math.random() * Math.floor(25))
    },
    gallery4: {
      id: 'gallery4',
      hasAltText: false,
      altText: 'Two friends taking a selfie and holding up peace signs in the middle of a snowy forest.',
      autogenerated: 'Two friends taking a selfie and holding up peace signs in the middle of a snowy forest.',
      link: require('./assets/images/gallery/pic4.jpg'),
      likes: Math.floor(Math.random() * Math.floor(300)),
      comments: Math.floor(Math.random() * Math.floor(25))
    },
    gallery5: {
      id: 'gallery5',
      hasAltText: false,
      altText: null,
      autogenerated: 'My sister and I laughing and hugging while standing at the top of a hill overlooking the San Francisco horizon.',
      link: require('./assets/images/gallery/pic5.jpg'),
      likes: Math.floor(Math.random() * Math.floor(300)),
      comments: Math.floor(Math.random() * Math.floor(25))
    },
    gallery6: {
        id: 'gallery6',
        hasAltText: false,
        altText: null,
        autogenerated: 'My sister and I laughing and hugging while standing at the top of a hill overlooking the San Francisco horizon.',
        link: require('./assets/images/gallery/pic6.jpeg'),
        likes: Math.floor(Math.random() * Math.floor(300)),
        comments: Math.floor(Math.random() * Math.floor(25))
      },
      gallery7: {
        id: 'gallery7',
        hasAltText: false,
        altText: null,
        autogenerated: 'My sister and I laughing and hugging while standing at the top of a hill overlooking the San Francisco horizon.',
        link: require('./assets/images/gallery/pic7.jpg'),
        likes: Math.floor(Math.random() * Math.floor(300)),
        comments: Math.floor(Math.random() * Math.floor(25))
      }
  }



  export {GALLERY}
