

const IMAGES = {
  iceCream: {
    id: 'iceCream',
    poster: 'gallery',
    caption: '10/10 would recommend!',
    feed: false,
    hasAltText: false,
    altText: null,
    autogenerated: 'Me holding a ##vanilla ice cream cone at the ##Santa ##Cruz ##Boardwalk on a ##sunny day.',
    custom: null,
    link: require('./assets/images/ice_cream.png'),
    thumbnail: require('./assets/images/ProfilePicture.png')
  },
  sydney1: {
    id: 'sydney1',
    poster: 'sydney',
    caption: 'Blue looks good on the sky (this guy)',
    feed: false,
    hasAltText: true,
    altText: 'Matias and Sydney smiling by a river and a balcony on a sunny day.',
    autogenerated: 'Matias and Sydney ##frowning by a ##river and a balcony on a ##cloudy day.',
    custom: null,
    link: require('./assets/images/feed/sydney1.png'),
    thumbnail: require('./assets/images/ProfilePicture.png')
  },
  sydney2: {
    id: 'sydney2',
    poster: 'sydney',
    caption: 'Utah rocks',
    feed: false,
    hasAltText: true,
    altText: 'An orange and red archway formed by rocks in Zion National Park.',
    autogenerated: 'An orange and red archway formed by rocks in ##Yellowstone ##National ##Park.',
    custom: null,
    link: require('./assets/images/feed/sydney2.png'),
    thumbnail: require('./assets/images/ProfilePicture.png')
  },
  sydney3: {
    id: 'sydney3',
    poster: 'sydney',
    caption: 'I\'ll look back on summer with rose-colored glasses',
    feed: false,
    hasAltText: true,
    altText: 'The silouette of me sitting on a dock and watching a pretty red and orange sunset over Lake Lavon.',
    autogenerated: 'The silouette of me sitting on a ##boat and watching a pretty red and orange ##sunset over ##Lake ##Lavon.',
    custom: null,
    link: require('./assets/images/feed/sydney3.png'),
    thumbnail: require('./assets/images/ProfilePicture.png')
  },
  sydney4: {
    id: 'sydney4',
    poster: 'sydney',
    caption: 'Sisterhood!',
    feed: false,
    hasAltText: true,
    altText: 'My sister and I hugging each other and wearing matching beanies in the snow.',
    custom: null,
    autogenerated: 'My sister and I ##hugging each other and wearing matching ##beanies in the ##snow.',
    link: require('./assets/images/feed/sydney4.png'),
    thumbnail: require('./assets/images/ProfilePicture.png')
  },
  sydney5: {
    id: 'sydney4',
    poster: 'sydney',
    caption: 'Look who I brought home today',
    feed: false,
    hasAltText: true,
    altText: 'Me kneeling down and hugging a husky in the snow.',
    autogenerated: 'Me kneeling down and ##hugging a ##dalmatian in the ##snow.',
    custom: null,
    link: require('./assets/images/feed/sydney5.png'),
    thumbnail: require('./assets/images/ProfilePicture.png')
  },
  gallery1: {
    id: 'gallery1',
    poster: 'gallery',
    caption: 'Took 8 hours, but the view was worth it!',
    feed: false,
    hasAltText: false,
    altText: null,
    autogenerated: 'A ##breathtaking view of ##snowcapped ##mountains towering over a ##green-blue lake on a ##warm day.',
    custom: null,
    link: require('./assets/images/gallery/pic1.png'),
    thumbnail: require('./assets/images/ProfilePicture.png')
  },
  gallery2: {
    id: 'gallery2',
    poster: 'gallery',
    caption: 'Never gets old',
    feed: false,
    hasAltText: false,
    altText: null,
    autogenerated: 'Jagged ##red and ##green rock formations dotted with ##trees and blanketed in ##snow.',
    custom: null,
    link: require('./assets/images/gallery/pic2.jpg'),
    thumbnail: require('./assets/images/ProfilePicture.png')
  },
  gallery3: {
    id: 'gallery3',
    poster: 'gallery',
    caption: 'I was stung by a bee 2 minutes after taking this pic lol',
    feed: false,
    hasAltText: false,
    altText: null,
    autogenerated: 'A blossoming ##yellow ##tulip in the middle of a ##field of ##golden ##sunflowers',
    custom: null,
    link: require('./assets/images/gallery/pic3.jpg'),
    thumbnail: require('./assets/images/ProfilePicture.png')
  },
  gallery4: {
    id: 'gallery4',
    poster: 'gallery',
    caption: 'The most photogenic dog I know',
    feed: false,
    hasAltText: false,
    altText: null,
    autogenerated: 'A cute ##golden ##retriever posing for a picture with ##his ##paws laid out in front.',
    custom: null,
    link: require('./assets/images/gallery/pic4.jpg'),
    thumbnail: require('./assets/images/ProfilePicture.png')
  },
  gallery5: {
    id: 'gallery5',
    poster: 'gallery',
    caption: 'Made a friend!!',
    feed: false,
    hasAltText: false,
    altText: null,
    autogenerated: 'Me ##snorkeling in the ##Great ##Barrier ##Reef alongside a ##shark in crystal clear waters.',
    custom: null,
    link: require('./assets/images/gallery/pic5.jpg'),
    thumbnail: require('./assets/images/ProfilePicture.png')
  },
  gallery6: {
    id: 'gallery6',
    poster: 'gallery',
    caption: 'A model... who, me??',
    feed: false,
    hasAltText: false,
    altText: null,
    autogenerated: 'The ##silhouette of my ##back as I turn to face the ##pink and ##brown ##sunset with puffy ##clouds',
    custom: null,
    link: require('./assets/images/gallery/pic6.jpeg'),
    thumbnail: require('./assets/images/ProfilePicture.png')
  },
  gallery7: {
    id: 'gallery7',
    poster: 'gallery',
    caption: 'LSJUMB 4 LIFE',
    feed: false,
    hasAltText: false,
    altText: null,
    autogenerated: 'A row of ##seven ##mascots of the ##Berkeley ##tree standing on ##Palm ##Drive.',
    custom: null,
    link: require('./assets/images/gallery/pic7.JPG'),
    thumbnail: require('./assets/images/ProfilePicture.png')
  },
  dani1: {
    id: 'dani1',
    poster: 'dani',
    caption: 'On top of the world!',
    feed: true,
    hasAltText: false,
    altText: null,
    autogenerated: 'My sister and I ##smiling and ##hugging while standing at the top of a hill overlooking the ##San ##Francisco ##horizon.',
    custom: null,
    link: require('./assets/images/feed/dani1.png'),
    thumbnail: require('./assets/images/feed/daniProf.png')
  },
  haeli1: {
    id: 'haeli1',
    poster: 'haeli',
    caption: 'Happy birthday to my kindred spirit <3',
    feed: true,
    hasAltText: true,
    altText: 'Two friends taking a selfie and holding up peace signs in the middle of a snowy forest.',
    autogenerated: '##Four friends taking a selfie and holding up ##peace ##signs in the middle of a ##snowy ##forest.',
    custom: null,
    link: require('./assets/images/feed/haeli1.png'),
    thumbnail: require('./assets/images/feed/haeliProf.png')
  },
}



export {IMAGES}
