const IMAGES = {
  iceCream: {
    id: 'iceCream',
    hasAltText: false,
    altText: null,
    autogenerated: 'Me holding a chocolate ice cream cone at the Santa Cruz Boardwalk on a sunny day.',
    link: require('./assets/images/ice_cream.png')
  }
}

export {IMAGES}
