

const IMAGES = {
  iceCream: {
    id: 'iceCream',
    poster: 'sydney',
    hasAltText: false,
    altText: null,
    autogenerated: 'Me holding a ##vanilla ice cream cone at the ##Santa ##Cruz ##Boardwalk on a ##sunny day.',
    link: require('./assets/images/ice_cream.png')
  },
  sydney1: {
    id: 'sydney1',
    hasAltText: true,
    altText: 'Matias and Sydney smiling by a river and a balcony on a sunny day.',
    autogenerated: 'Matias and Sydney smiling by a river and a balcony on a sunny day.',
    link: require('./assets/images/feed/sydney1.png')
  },
  sydney3: {
    id: 'sydney3',
    hasAltText: true,
    altText: 'An orange and red archway formed by rocks in Zion National Park.',
    autogenerated: 'An orange and red archway formed by rocks in Zion National Park.',
    link: require('./assets/images/feed/sydney3.png')
  },
  haeli1: {
    id: 'haeli1',
    hasAltText: true,
    altText: 'Two friends taking a selfie and holding up peace signs in the middle of a snowy forest.',
    autogenerated: 'Two friends taking a selfie and holding up peace signs in the middle of a snowy forest.',
    link: require('./assets/images/feed/haeli1.png')
  },
  dani1: {
    id: 'dani1',
    hasAltText: false,
    altText: null,
    autogenerated: 'My sister and I laughing and hugging while standing at the top of a hill overlooking the San Francisco horizon.',
    link: require('./assets/images/feed/dani1.png')
  }
}



export {IMAGES}
