import React, { Component } from 'react';
import { Alert, Image, Text, View, StyleSheet, ScrollView, Dimensions, TouchableOpacity } from 'react-native';
import * as Font from 'expo-font';
import { Container, Content } from 'native-base'
import CardComponent from './src/components/CardComponent'
//import { Audio } from ''
import { Card, ListItem, Button, Icon } from 'react-native-elements'
import NewGalleryPhoto from './src/components/NewGalleryPhoto'
import ToggleFilter from './src/components/ToggleFilter'

import { GALLERY } from './GALLERY.js';
import { styles } from './Styles.js';

export default class NewPostFilter extends Component {
  constructor(props) {
    super(props);
    this.state = {
      selectedImageLink: require('./assets/images/gallery/pic1.png'),
    }
    //var selectedImage = props.navigation.state.params.selectedImage;
    this.selectedImage = this.selectedImage.bind(this);
  }
  selectedImage(photo) {
    this.setState({ selectedImageLink: photo.link })
    //Alert.alert(`${photo.id} kissed`);
  }
  hardCodedGallery() {
    const GALLERY = {
      gallery1: {
        id: 'gallery1',
        poster: 'sydney',
        hasAltText: false,
        altText: null,
        autogenerated: 'Me holding a ##vanilla ice cream cone at the ##Santa ##Cruz ##Boardwalk on a ##sunny day.',
        link: require('./assets/images/gallery/pic1.png')
      }
    }
    return GALLERY
  }
  render() {
    let images = [];
    for (let i = 0; i < 6; i++) {
      for (const [key, value] of Object.entries(this.hardCodedGallery())) {
        images.push(
          <NewGalleryPhoto key={`${i}${key}`} photo={value} isNewPhoto={true} selectedImage={this.selectedImage} />
        );
      }
    }
    return (
      <View style={styles.container}>
        <View style={styles.selectedImageContainer}>
          <Image
            style={styles.selectedGalleryPhoto}
            source={this.state.selectedImageLink}
          />
        </View>
        <View style={styles.horizontalScroll}>
          <ScrollView horizontal={true}>
            <View>
              <View style={{ justifyContent: 'center', margin: 1 }}>
                <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
                  {images}
                </View>
              </View>
            </View>
          </ScrollView>
        </View>
        <View style={styles.editToggle}>
          <ToggleFilter
            selected='left'
            iconLeft={require('./assets/images/GallerySelected.png')}
            iconRight={require('./assets/images/AltIconUnselected.png')}
            navigation={this.props.navigation} />
        </View>
      </View>
    );
  }
}
export { NewPostFilter };